### ISSUE TITLE
Provide a matrix to turn dark greys to pure black for OLED screens

### ISSUE THREAD

**Issue by csdvrx** [mlaily/NegativeScreen#26]
A frequent concern with dark themes on OLED screens is that they try to look better or non-OLED screens, so they don't use true black but darkish greys instead. However these do not look as nice as true black on OLED screens: the dark greys can be too bright, and also do not allow for as much power saving due to all the pixels being still "on" (which is more of a problem in high resolutions like 4k)

Therefore, "true black" themes specially made for OLED often coexist with dark themes on some of the best know apps, but the problem remains for websites which offer little to no configuration options (if they even support dark themes!)

As a consequence, it would be extremely helpful to have a matrix doing this, if it's ever possible (as I believe the curve values are required to bring low RGB to 0 i.e. true black)

**Comment by mlaily** [comment]
Well, I guess you could try something like that:
```
{  1.2,  0.0,  0.0,  0.0,  0.0 }
{  0.0,  1.2,  0.0,  0.0,  0.0 }
{  0.0,  0.0,  1.2,  0.0,  0.0 }
{ -0.2, -0.2, -0.2,  1.0,  0.0 }
{  0.0,  0.0,  0.0,  0.0,  1.0 }
```

It will make dark colors darker (and the darkest will turn to complete black) but keep brighter colors relatively unchanged.

Try it in https://zerowidthjoiner.net/colormatrix-viewer to see what I mean.  
You can tune the matrix as you want by changing the values so each column's sum is 1...

I will be closing this now, because that's not a matrix I plan to add as a default. (Maybe I will change my mind if/when I get an OLED display :) )

**Comment by csdvrx** [comment]
Hello

After moving to a different OLED device, I just wanted to tell you how DELIGHTFUL this transformation matrix is when bumped to -0.4/1.4!

Now the only small issue is how to quickly do the toggle on that device, a tablet with no keyboard, and with the taskbar often hidden to avoid OLED burn-in.

After trying a few things, I realized the notifications menu (Win N, or slide the right edge of the screen inwards) or the action menu (Win A) was a great way to control things!

Some apps like media players put a few buttons there, so I was wondering if it would be possible to add notifications support to negativescreen?

A few modes could be assigned their own buttons either there or in notifications cf
https://smsagent.blog/2020/10/20/adding-your-own-caller-app-for-custom-windows-10-toast-notifications/ for a powershell example and https://docs.microsoft.com/en-us/uwp/api/windows.ui.notifications.toastnotification?view=winrt-22000 for the API.

In the worst case, if no button can be added, the notification could simply list the current mode and toggle inversion when it’s clicked – then send a new notification with the new mode.

It’s just a wild idea, but I though you could be interested!

Thanks again for negativescreen!
