### ISSUE TITLE
Negative Screen in a specific area

### ISSUE THREAD

**Issue by devyokan** [mlaily/NegativeScreen#34]
A specific part of my monitor has the negative effect, is it possible for me to apply the negative screen to just a specific area?

I tried AutoHotkey but it didn't work very well, at least the code i tried took images all the time and placed them in the location but the specific area kept flashing.

**Comment by mlaily** [comment]
Hi!

You are not the first one to ask this kind of question.  
Unfortunately the answer is no at the moment, maybe one day.

I'm going to close this issue. There are multiple feature requests already covering the topic:
- https://github.com/mlaily/NegativeScreen/issues/10
- https://github.com/mlaily/NegativeScreen/issues/17
- https://github.com/mlaily/NegativeScreen/issues/5
