### ISSUE TITLE
Does not work with FastStone Capture

### ISSUE THREAD

**Issue by dfcreative** [mlaily/NegativeScreen#8]
Hi @mlaily!
Thank you for the awesome work!
Recently I hoped to use the tool to speed up my workflow by taking negative screenshots via this tool and fast stone capture, but sadly found out that they don't work well with each other.
Is there any way to make them work well? If no, are there workarounds or any plans for adding screenshots support? 
Thanks!

**Comment by mlaily** [comment]
Mmh, I don't know about fast stone capture, but using the Print Screen key works as expected on my machine. (up to date Windows 10 x64)
Maybe fast stone capture uses some lower level technique? And maybe this can be configured...
